# # name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
   

#       - name: Install dependencies
#         run: npm install
#         working-directory: ./adil

#       - name: Build
#         run: npm run build --if-present
#         working-directory: ./adil

#       - uses: mr-smithers-excellent/docker-build-push@v6
#         with:
#           image: adiilkhan/practicecicd
#           registry: docker.io
#           username:

# name: Docker Build and Push

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2
      
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         directory : ./adil/Dockerfile
#     - name: Build Docker image
#       run: docker build -t adiilkhan/practicecicd:latest .
      
#     - name: Push Docker image to Docker Hub
#       run: docker push adiilkhan/practicecicd:latest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: ng build --prod
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: adiilkhan/practicecicd:tagname
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
