name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        

      # - name: Set permissions for package.json
      #   run: chmod 644 package.json

      - name: NPM
        working-directory: ./adil
        run: |
          npm install
          npm run build --if-present

      - name: Install dependencies
        if: success()
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test
